version: '3'

networks:
  kafka-net:
    driver: bridge

services:
  kafka:
    image: bitnami/kafka:2.1.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CREATE_TOPICS=mytopic:1:1
      - KAFKA_KRAFT_CLUSTER_ID=order-ms
    depends_on:
      - zookeeper

  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes


  db:
    image: postgres:latest
    container_name: my-postgres-db
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: mydb
    ports:
      - '5433:5432' # Map PostgreSQL's port to the host
    command: -p 5433
    expose:
      - 5433
  app:
    build: ./user-ms
    container_name: my-nestjs-app
    ports:
      - '3000:3000'
    depends_on:
      - db
      - kafka
  order:
    build: ./order-service
    container_name: order-ms
    ports:
      - '3001:3001'
    depends_on:
      - db
      - kafka
    
  product:
    build: ./product-service
    container_name: product-ms
    ports:
      - '3002:3002' # Map the app's port to the host
    depends_on:
      - db
      - kafka